title: A Moment on Malware
author:
  name: Maarten Broekman
  email: maarten@broekman.us
theme: jekyll-theme-slate
markdown: kramdown
social_links:
  linkedin: maartenjbroekman
  github:  mjbroekman
  youtube: MaartenBroekman
  facebook: maarten.j.broekman
  twitter: mjbroekman
show_downloads: false
