title: A Moment on Malware
author:
  name: Maarten Broekman
  email: maarten@broekman.us
theme: jekyll-theme-primer
markdown: kramdown
social_links:
  linkedin: maartenjbroekman
  github:  mjbroekman
  youtube: MaartenBroekman
  facebook: maarten.j.broekman
  twitter: mjbroekman
show_downloads: false
github.is_project_page: false
lang: en
github.owner_name: mjbroekman
github.private: true
github.license: cc-by-sa-4.0
